const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-balance/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){h.c.setGuess(h.c.puzzle().value);h.c.check();assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('balance'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{balance:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'wrong');h.c.setGuess(99);h.c.setGuess(NaN);assert.equal(h.run('guess'),0);h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.setGuess(1);h.e.retry.onclick();assert.equal(h.run('guess'),0);assert(h.e.hints.hidden);h.c.setGuess(4);const snap=h.run('JSON.stringify([stage,guess,variant])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([stage,guess,variant])'),snap);solve(h);assert(h.c.OrionProgress.has('balance')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('balance'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('balance'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('balance'));assert.equal(h.run('stage'),0);
}
for(let v=0;v<6;v++)for(let s=0;s<3;s++)for(let n=0;n<=9;n++){const h=setup();h.run(`variant=${v};stage=${s};resetTrial()`);h.c.setGuess(n);h.c.check();const expected=[2+v,1+(v+2)%8,1+(v+4)%8][s];assert.equal(h.run('solved'),n===expected);}
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('balance'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS balance: all 180 guesses, six sets, both languages, wrong/retry/hints, rewards, persistence, replay/reset, failed save.');
