const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-buoyancy/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){h.c.adjust(1);h.c.check();assert(h.run('solved'));assert(!h.c.OrionProgress.has('afloat'));h.e.next.onclick();h.c.adjust(1);h.c.check();assert(!h.run('solved'));h.c.adjust(10);h.c.check();assert(h.run('solved'));assert(!h.c.OrionProgress.has('afloat'));h.e.next.onclick();h.c.adjust(h.c.target()+1);h.c.check();assert(h.run('solved'));}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{buoyancy:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);const initial=h.run('amount');for(const n of [0,11,1.5,NaN])h.c.adjust(n);assert.equal(h.run('amount'),initial);h.c.check();assert(!h.run('solved'));h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('amount'),initial);h.e.retry.onclick();assert(h.e.hints.hidden);solve(h);assert(h.c.OrionProgress.has('afloat')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('afloat'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('afloat'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('afloat'));assert.equal(h.run('stage'),0);}
// Independent model: weight m*g versus maximum displaced-water weight rho*V*g.
let trials=0;const journeys=new Set();for(let v=0;v<6;v++){const h=setup();h.run(`variant=${v}`);journeys.add([0,1,2].map(s=>h.c.target(v,s)).join());for(let s=0;s<3;s++)for(let a=1;a<=10;a++){h.run(`stage=${s};resetTrial()`);h.c.adjust(a);const m=h.c.mass(),vol=h.c.volume(),weight=m*9.81,maxBuoyancy=vol*9.81,o=weight<maxBuoyancy?'float':weight>maxBuoyancy?'sink':'neutral';assert.equal(h.c.outcome(),o);h.c.check();assert.equal(h.run('solved'),s===0?o==='float':s===1?false:o==='float'&&vol===m+1);trials++;}}assert.equal(journeys.size,6);
const h=setup();h.run('stage=1;resetTrial()');h.c.adjust(1);h.c.check();h.c.check();assert(!h.run('solved'));h.c.OrionI18n.set('zh-Hant');assert(h.run('seen.sink'));h.c.adjust(10);h.c.check();assert(h.run('solved'));h.run('stage=1;resetTrial()');assert(!h.run('seen.sink||seen.float'));
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('afloat'));assert.equal(setup('en','broken').run('variant'),0);
console.log(`PASS buoyancy: ${trials} designs against force comparison, six distinct journeys, neutral case, paired evidence, both languages, hints/retry, reward/persistence/reset and failed saves.`);
