const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(language='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':language};if(saved)data['orion-expedition-progress-v1']=saved;const element=()=>({value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,open:false,attrs:{},classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=v},addEventListener(){},focus(){}});const c={navigator:{language},Event:class{constructor(type){this.type=type}},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},document:{documentElement:{},getElementById:id=>e[id]??=element(),querySelectorAll:()=>[]},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:event=>(events[event.type]??[]).forEach(f=>f(event))};c.window=c;vm.createContext(c);for(const path of ['dist/shared/i18n.js','dist/shared/progress.js','dist/games/orion-circuits/game.js'])vm.runInContext(fs.readFileSync(path,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}
// Independent graph traversal: a lamp lights iff removing the lamp leaves its two ends
// connected respectively to opposite battery terminals by wires and closed switches.
function expected(stage,sw){const edges=stage===0?[['p','a',sw[0]],['a','b',sw[1]]]:stage===1?[['p','a',sw[0]],['p','b',sw[1]]]:[['p','j',sw[2]],['j','a',sw[0]],['j','b',sw[1]]];const lamps=stage===0?[['b','n']]:[['a','n'],['b','n']];function connected(x,y){const seen=new Set([x]),q=[x];while(q.length){const n=q.shift();for(const[a,b,closed]of edges){if(!closed)continue;const next=a===n?b:b===n?a:null;if(next&&!seen.has(next)){seen.add(next);q.push(next);}}}return seen.has(y);}return lamps.map(([a,b])=>connected('p',a)&&connected('n',b)||connected('p',b)&&connected('n',a));}
const model=setup();for(let s=0;s<3;s++)for(let mask=0;mask<8;mask++){const sw=[0,1,2].map(i=>!!(mask&(1<<i)));assert.deepEqual(Array.from(model.c.lights(s,sw)),expected(s,sw));}
function complete(h){for(let s=0;s<3;s++){const goal=h.c.targetFor(h.run('variant'),s),wanted=s===0?[true,true,false]:[goal[0],goal[1],s===2];for(let i=0;i<(s===2?3:2);i++)if(h.run(`switches[${i}]`)!==wanted[i])h.c.toggle(i);h.c.check();assert(h.run('solved'));if(s<2)h.e.next.onclick();}assert(h.c.OrionProgress.has('spark'));}
const signatures=new Set();for(let v=0;v<6;v++)signatures.add(JSON.stringify([model.c.initialFor(v,0),model.c.targetFor(v,1),model.c.targetFor(v,2)]));assert.equal(signatures.size,6);
for(const language of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(language,JSON.stringify({version:1,sigils:['future'],variants:{circuits:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden&&h.e.notes.hidden);h.e.next.onclick();assert.equal(h.run('stage'),0);h.c.check();assert(!h.run('solved'));assert.equal(h.run('state'),'wrong');
 const old=h.run('JSON.stringify(switches)');for(const i of [-1,2,3,1.5,NaN,'0'])h.c.toggle(i);assert.equal(h.run('JSON.stringify(switches)'),old);
 h.e.hint.onclick();h.e.hint.onclick();h.e.hint.onclick();assert(h.e.hint.disabled);assert(!h.e.hints.hidden);assert.match(h.e.hints.innerHTML,/A/);h.c.toggle(0);const snapshot=h.run('JSON.stringify([variant,stage,switches,hintDepth])');h.c.OrionI18n.set(language==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([variant,stage,switches,hintDepth])'),snapshot);h.e.retry.onclick();assert.equal(h.run('hintDepth'),0);assert.equal(h.run('JSON.stringify(switches)'),old);
 complete(h);assert(h.c.OrionProgress.has('future'));assert.equal(h.e.progressBar.value,3);assert(!h.e.notes.hidden);h.c.check();h.c.toggle(0);assert.equal(h.c.OrionProgress.read().sigils.length,2);
 const reload=setup(language,h.data['orion-expedition-progress-v1']);assert.equal(reload.run('variant'),v);assert(reload.c.OrionProgress.has('spark'));h.e.replay.onclick();const next=h.run('variant');assert.notEqual(next,v);assert(h.c.OrionProgress.has('spark'));complete(h);h.c.OrionProgress.reset();h.c.dispatchEvent({type:'pageshow'});assert.notEqual(h.run('variant'),next);assert(!h.c.OrionProgress.has('spark'));assert(h.e.reward.hidden&&h.e.hints.hidden);complete(h);
}
const other=setup();other.c.toggle(0);other.e.hint.onclick();const before=other.run('JSON.stringify([variant,stage,switches,hintDepth])');other.c.OrionProgress.earn('echo');other.c.dispatchEvent({type:'storage',key:'orion-expedition-progress-v1'});assert.equal(other.run('JSON.stringify([variant,stage,switches,hintDepth])'),before);other.c.OrionProgress.reset();other.c.dispatchEvent({type:'storage',key:'orion-expedition-progress-v1'});assert.equal(other.run('hintDepth'),0);
const blocked=setup('en',undefined,true);complete(blocked);assert.match(blocked.e.saveStatus.textContent,/could not save/);assert(!blocked.e.retrySave.hidden);const failedBefore=blocked.run('JSON.stringify(OrionProgress.read())');assert.equal(blocked.c.OrionProgress.reset(),false);assert.equal(blocked.run('JSON.stringify(OrionProgress.read())'),failedBefore);blocked.c.localStorage.setItem=(k,v)=>blocked.data[k]=v;blocked.e.retrySave.onclick();assert(blocked.e.retrySave.hidden);assert.match(blocked.e.saveStatus.textContent,/saved/);complete(setup('zh-Hant','bad json'));
const resets=setup();for(let i=0;i<100;i++){const v=resets.c.OrionProgress.variant('circuits');assert(resets.c.OrionProgress.reset());assert.notEqual(resets.c.OrionProgress.variant('circuits'),v);}
console.log('PASS circuits: independent graph oracle for every switch combination, six distinct variants in both languages, wrong/invalid/retry, hints, three-panel rewards, reload/replay/reset, unknown sigils, unrelated awards, corrupt/blocked storage and save retry.');
