const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-foodchains/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let i=0;i<3;i++){for(const n of h.c.target())h.c.choose(n);h.c.check();assert(h.run('solved'));if(i<2){assert(!h.c.OrionProgress.has('connection'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{foodchains:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'incomplete');for(const n of [-1,9,NaN])h.c.choose(n);assert.equal(h.run('chosen.length'),0);const n=h.c.deck()[0];h.c.choose(n);h.c.choose(n);assert.equal(h.run('chosen.length'),1);h.e.hint.onclick();assert(!h.e.hints.hidden);const before=h.run('JSON.stringify(chosen)');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify(chosen)'),before);h.c.remove(0);assert.equal(h.run('chosen.length'),0);h.e.retry.onclick();assert(h.e.hints.hidden);solve(h);assert(h.c.OrionProgress.has('connection')&&h.c.OrionProgress.has('future'));h.c.check();h.c.remove(0);assert(h.run('solved'));assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('connection'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('connection'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('connection'));assert.equal(h.run('stage'),0);
}
// Explicit habitat oracle, independent of the game's target and check functions.
const valid=[[0,1,2],[3,4,5],[6,7,8]],journeys=new Set();let examined=0;
for(let v=0;v<6;v++){const h=setup();h.run(`variant=${v}`);const journey=[];for(let s=0;s<3;s++){h.run(`stage=${s};resetTrial()`);const habitat=h.c.habitat(),deck=Array.from(h.c.deck());journey.push(habitat);assert.equal(new Set(deck).size,6);assert(valid[habitat].every(n=>deck.includes(n)));let winners=0;for(const a of deck)for(const b of deck)for(const c of deck){if(a===b||a===c||b===c)continue;h.c.resetTrial();h.c.choose(a);h.c.choose(b);h.c.choose(c);h.c.check();const expected=[a,b,c].every((n,i)=>n===valid[habitat][i]);assert.equal(h.run('solved'),expected);if(expected)winners++;examined++;}assert.equal(winners,1);}assert.equal(new Set(journey).size,3);journeys.add(journey.join());}assert.equal(journeys.size,6);assert.equal(examined,2160);
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('connection'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS foodchains: 2160 ordered selections, six sets, both languages, hints/remove/retry, complete rewards, persistence/reset and failed-save recovery.');
