const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang},timers=new Map();let next=0; if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:1,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={setTimeout:f=>{timers.set(++next,f);return next},clearTimeout:id=>timers.delete(id),navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-fox/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,timers,run:s=>vm.runInContext(s,c),flush(){let guard=100;while(timers.size){assert(guard-->0);const[id,f]=[...timers][0];timers.delete(id);f();}}};}
// Independent breadth-first search uses map coordinates, not the game's solution helper.
function bfs(map){const queue=[[map[0],[]]],seen=new Set([map[0].join(',')]),dirs=[[0,-1],[1,0],[0,1],[-1,0]];while(queue.length){const[pos,steps]=queue.shift();if(pos.join(',')===map.at(-1).join(','))return steps;dirs.forEach(([dx,dy],d)=>{const n=[pos[0]+dx,pos[1]+dy],k=n.join(',');if(!seen.has(k)&&map.some(p=>p.join(',')===k)){seen.add(k);queue.push([n,[...steps,d]]);}});}throw Error('unreachable');}
function loadSolution(h){const steps=bfs(h.c.route());for(let i=0;i<steps.length;){let n=1;while(n<3&&steps[i+n]===steps[i])n++;h.c.addCommand(steps[i],n);i+=n;}}
function solve(h){for(let s=0;s<3;s++){loadSolution(h);h.c.run();h.flush();assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('footprint'));h.e.next.onclick();}}}
const journeys=new Set();
for(let v=0;v<8;v++)for(const lang of ['en','zh-Hant']){const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{fox:v}}));journeys.add(h.run('JSON.stringify([route(variant,0),route(variant,1),route(variant,2)])'));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.run();assert.equal(h.run('state'),'empty');h.c.addCommand(99);h.c.addCommand(0,0);assert.equal(h.run('program.length'),0);h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.addCommand(0);h.c.removeCommand(0);assert.equal(h.run('program.length'),0);h.e.clear.onclick();assert(h.e.hints.hidden);
 const map=h.c.route(),bad=[0,1,2,3].find(d=>!h.c.advance(map[0],d,map));h.c.addCommand(bad);h.c.run();h.flush();assert.equal(h.run('state'),'bump');assert(!h.run('solved'));h.e.clear.onclick();
 loadSolution(h);h.c.run();const snapshot=h.run('JSON.stringify([program,position,stage,variant])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([program,position,stage,variant])'),snapshot);h.e.stop.onclick();h.flush();assert(!h.run('solved'));assert.equal(h.run('state'),'stopped');h.e.clear.onclick();solve(h);assert(h.c.OrionProgress.has('footprint')&&h.c.OrionProgress.has('future'));h.c.run();h.flush();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('footprint'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);const newV=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),newV);assert(h.c.OrionProgress.has('footprint'));loadSolution(h);h.c.run();h.c.OrionProgress.reset();h.c.syncProgress();h.flush();assert(!h.run('solved')&&!h.c.OrionProgress.has('footprint'));assert.equal(h.run('stage'),0);assert.notEqual(h.run('variant'),newV);}
assert.equal(journeys.size,8);
// Counted moves cannot jump over hedges; reward needs the final position, not merely visiting treasure.
const h=setup();assert.equal(h.c.simulate([{d:1,n:3}]).reason,'bump');assert.equal(h.c.simulate([{d:1,n:1}]).reason,'short');assert.equal(h.c.simulate([{d:1,n:0}]).success,false);const p=h.c.solution();assert(h.c.simulate(p).success);assert.equal(h.c.simulate([...p,{d:3,n:1}]).success,false);for(let v=0;v<8;v++)for(let s=0;s<3;s++){h.run(`variant=${v};stage=${s}`);assert(h.c.simulate(h.c.solution()).success,'generated hints must solve each map');}
// Invalid/overflow edits, interrupted stale callbacks and storage recovery.
h.run('resetMission(0)');for(let i=0;i<13;i++)h.c.addCommand(1);assert.equal(h.run('program.length'),12);assert.equal(h.run('state'),'full');h.e.clear.onclick();loadSolution(h);h.c.run();const stale=[...h.timers.values()][0];h.e.stop.onclick();stale();assert.equal(h.run('steps'),0);
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('footprint'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS fox: independent route search, 8 sets × 2 languages, hints, collision/short/invalid/stop paths, complete rewards, replay/reset, stale callbacks and failed-save recovery.');
