const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,style:{},classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-fractions/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}


function fill(h,n,d){h.c.partition(d);for(let i=0;i<n;i++)h.c.toggle(i);h.c.check();}
function solve(h){for(let stage=0;stage<3;stage++){const [n,d]=h.c.target();const ds=[2,3,4,6,8,12].filter(x=>x!==d&&n*x%d===0);fill(h,n*ds[0]/d,ds[0]);if(stage===2){assert(!h.run('solved'));h.c.check();assert.equal(h.run('state'),'duplicate');assert(!h.c.OrionProgress.has('unity'));fill(h,n*ds[1]/d,ds[1]);}else h.e.next.onclick();}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{fractions:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'less');h.c.partition(5);assert.equal(h.run('denominator'),4);h.c.toggle(-1);h.c.toggle(99);assert.equal(h.c.count(),0);h.c.toggle(0);h.e.hint.onclick();h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.c.count(),1);assert(!h.e.hints.hidden);h.e.retry.onclick();assert(h.e.hints.hidden);solve(h);assert(h.run('solved'));assert(h.c.OrionProgress.has('unity')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('unity'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('unity'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('unity'));}
// Independent rational oracle checks every numerator for all offered partitions.
let trials=0;const journeys=new Set();for(let v=0;v<6;v++){const h=setup();h.run(`variant=${v}`);journeys.add([0,1,2].map(s=>h.c.target(v,s).join('/')).join());for(let s=0;s<3;s++){h.run(`stage=${s}`);const [n,d]=h.c.target();for(const den of [2,3,4,6,8,12])for(let num=0;num<=den;num++){h.c.resetTrial();fill(h,num,den);const equal=num/den===n/d&&den!==d;assert.equal(h.run('matches.length'),equal?1:0);assert.equal(h.run('solved'),equal&&s<2);trials++;}}}assert.equal(journeys.size,6);
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('unity'));assert.equal(setup('en','broken').run('variant'),0);
console.log(`PASS fractions: ${trials} rational comparisons, six journeys, final distinct evidence, both languages, replay/reset/persistence and save failure.`);
