const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-gears/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){const g=h.c.target();h.c.chooseSize([2,1,.5].indexOf(g.speed));if(h.run('idler')!==g.cw)h.c.toggleIdler();h.c.check();assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('motion'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{gears:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'wrong');const initial=h.run('JSON.stringify([size,idler])');h.c.chooseSize(99);h.c.chooseSize(NaN);assert.equal(h.run('JSON.stringify([size,idler])'),initial);h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.chooseSize(1);h.e.retry.onclick();assert.equal(h.run('JSON.stringify([size,idler])'),initial);assert(h.e.hints.hidden);const snap=h.run('JSON.stringify([stage,size,idler,variant])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([stage,size,idler,variant])'),snap);h.e.pause.onclick();assert(h.run('paused'));solve(h);assert(h.c.OrionProgress.has('motion')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('motion'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('motion'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('motion'));assert.equal(h.run('stage'),0);
}
// Independent gear law: 12 / output teeth; one mesh reverses, two restore direction.
const journeys=new Set();
for(let v=0;v<6;v++){const j=[];for(let s=0;s<3;s++){for(let size=0;size<3;size++)for(const idler of [false,true]){const h=setup();h.run(`variant=${v};stage=${s};resetTrial();size=${size};idler=${idler}`);const actual=h.c.output();assert.equal(actual.speed,12/[6,12,24][size]);assert.equal(actual.cw,idler);const g=h.c.target();h.c.check();assert.equal(h.run('solved'),actual.speed===g.speed&&actual.cw===g.cw);}const h=setup();j.push(h.c.target(v,s));}journeys.add(JSON.stringify(j));}
assert.equal(journeys.size,6);
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('motion'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS gears: 108 physical configurations, six sets, both languages, hints/retry/pause, all-three-seal reward, replay/reset/persistence and failed save recovery.');
