const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(language='en',blocked=false,saved){const elements={},events={},data={'orion-expedition-language':language};if(saved)data['orion-expedition-progress-v1']=saved;const element=()=>({value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,open:false,attrs:{},listeners:{},setAttribute(k,v){this.attrs[k]=v},addEventListener(k,f){this.listeners[k]=f},focus(){},classList:{toggle(){}}});const predictions=['left','balanced','right'].map(p=>Object.assign(element(),{dataset:{prediction:p}}));const c={navigator:{language},Event:class{constructor(type){this.type=type}},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},document:{documentElement:{},getElementById:id=>elements[id]??=element(),querySelectorAll:q=>q==='[data-prediction]'?predictions:[]},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:event=>(events[event.type]??[]).forEach(f=>f(event))};c.window=c;vm.createContext(c);for(const f of ['dist/shared/i18n.js','dist/shared/progress.js','dist/games/orion-levers/game.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c);const run=s=>vm.runInContext(s,c);return{c,e:elements,data,run,choose(m,d,p='balanced'){elements.mass.value=String(m);elements.distance.value=String(d);c.changeSetting();c.testBeam();}};}
function finalStage(h){h.choose(2,3);h.e.next.onclick();h.choose(2,4);h.e.next.onclick();}
function complete(h){finalStage(h);h.choose(2,6);h.choose(4,3);}
for(const lang of ['en','zh-Hant']){const h=setup(lang),{c,e,run}=h;assert(e.hints.hidden);assert(e.notes.hidden);assert(e.reward.hidden);c.testBeam();assert.equal(run('feedback'),'observe');h.choose(2,1,'right');assert.equal(run('feedback'),'observe');assert.equal(e.beam.attrs.transform,'rotate(-9 320 121)');h.choose(2,6,'right');assert.equal(run('feedback'),'observe');assert.equal(e.beam.attrs.transform,'rotate(9 320 121)');h.choose(2,0);assert.equal(run('feedback'),'invalid');h.choose(2,2,'left');e.hint.onclick();c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(run('hintDepth'),1);assert.equal(run('distance'),2);assert(run('history.length')>0);c.OrionProgress.earn('future');finalStage(h);h.choose(2,6);assert.equal(run('solutions.length'),1);assert(!c.OrionProgress.has('ingenuity'));h.choose(2,6);assert.equal(run('feedback'),'duplicate');assert.equal(run('solutions.length'),1);h.choose(4,3);assert(!e.reward.hidden);assert(!e.notes.hidden);assert(c.OrionProgress.has('ingenuity'));assert(c.OrionProgress.has('future'));h.c.testBeam();assert.equal(c.OrionProgress.read().sigils.length,2);assert(setup(lang,false,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('ingenuity'));e.replay.onclick();assert(e.hints.hidden);assert(c.OrionProgress.has('ingenuity'));complete(h);assert(c.OrionProgress.reset());c.dispatchEvent({type:'storage',key:'orion-expedition-progress-v1'});assert.equal(run('stage'),0);assert(e.reward.hidden);complete(h);assert(c.OrionProgress.has('ingenuity'));}
const expected=[['2:3'],['2:4'],['2:6','3:4','4:3']];const physics=setup();for(let s=0;s<3;s++){physics.run(`stage=${s}`);const found=[];for(let m=1;m<=4;m++)for(let d=1;d<=6;d++)if((s===2||m===2)&&physics.c.outcome(m,d)==='balanced')found.push(`${m}:${d}`);assert.deepEqual(found,expected[s]);}
const b=setup('zh-Hant',true);complete(b);assert.match(b.e.saveStatus.textContent,/無法儲存/);assert(!b.e.retrySave.hidden);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert.match(b.e.saveStatus.textContent,/已存入/);assert(b.e.retrySave.hidden);
const corrupt=setup('en',false,'bad json');complete(corrupt);assert(corrupt.c.OrionProgress.has('ingenuity'));const other=setup();other.choose(2,2,'left');other.c.OrionProgress.earn('echo');other.c.dispatchEvent({type:'storage',key:'orion-expedition-progress-v1'});assert.equal(other.run('distance'),2);other.c.OrionProgress.reset();other.c.dispatchEvent({type:'pageshow'});assert.equal(other.run('distance'),1);
console.log('PASS: all lever solutions/directions, direct balance, invalid settings, distinct designs, bilingual state/hints, idempotent/persistent rewards, replay, collection reset, other-tab awards, corrupt/blocked storage and retry.');
const direct=setup();direct.c.adjustMass(1);assert.equal(direct.run('mass'),2);
const diagram=direct.e.diagram;diagram.getBoundingClientRect=()=>({left:0,width:640});diagram.setPointerCapture=()=>{};
const event=(x,y)=>({button:0,pointerId:1,clientX:x,clientY:y});
diagram.listeners.pointerdown(event(363,100));diagram.listeners.pointermove(event(449,100));assert.equal(direct.run('distance'),3);assert(!direct.run('solved'));diagram.listeners.pointercancel();assert.equal(direct.run('distance'),1);assert(!direct.run('solved'));
diagram.listeners.pointerdown(event(363,100));diagram.listeners.pointerup(event(449,100));assert(direct.run('solved'));
direct.run('stage=2;resetStage()');diagram.listeners.pointerdown(event(363,150));diagram.listeners.pointermove(event(365,86));assert.equal(direct.run('mass'),3);assert.equal(direct.run('distance'),1);diagram.listeners.pointercancel();assert.equal(direct.run('mass'),1);
diagram.listeners.pointerdown(event(363,150));diagram.listeners.pointerup(event(363,54));assert.equal(direct.run('mass'),4);diagram.listeners.pointerdown(event(363,54));diagram.listeners.pointerup(event(363,118));assert.equal(direct.run('mass'),2);
direct.e.distance.value='6';direct.e.distance.listeners.input();assert(!direct.run('solved'));assert.equal(direct.run('solutions.length'),0);direct.e.distance.listeners.change();assert.equal(direct.run('solutions.length'),1);direct.c.OrionI18n.set('zh-Hant');assert.match(direct.e.massValue.textContent,/2/);
console.log('PASS: live drag, vertical weight changes, axis locking, cancellation without reward, release balance, slider completion and language preservation.');
