const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-light/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){const wanted=h.c.target();for(const b of [1,2,4])if((h.run('mask')&b)!==(wanted&b))h.c.toggle(b);h.c.check();assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('radiance'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{light:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'wrong');h.c.toggle(99);assert.equal(h.run('mask'),0);h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.toggle(1);h.e.retry.onclick();assert.equal(h.run('mask'),0);assert(h.e.hints.hidden);h.c.toggle(4);const snapshot=h.run('JSON.stringify([stage,mask,variant,history])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([stage,mask,variant,history])'),snapshot);solve(h);assert(h.c.OrionProgress.has('radiance')&&h.c.OrionProgress.has('future'));h.c.check();h.c.toggle(1);assert.equal(h.run('mask'),7);assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('radiance'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('radiance'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('radiance'));assert.equal(h.run('stage'),0);
}
const h=setup();const expected=['Dark · no light','Red','Green','Yellow','Blue','Magenta','Cyan','White'];const hex=['#000','#f00','#0f0','#ff0','#00f','#f0f','#0ff','#fff'];for(let m=0;m<8;m++){h.c.resetTrial();for(const b of [1,2,4])if(m&b)h.c.toggle(b);assert.equal(h.run('mask'),m);assert(h.e.reading.innerHTML.includes(expected[m]));assert(h.e.reading.innerHTML.includes(hex[m]));h.c.check();assert.equal(h.run('solved'),m===3);}const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('radiance'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS light: all eight RGB outcomes, six complete sets, both languages, invalid/wrong/retry, hidden hints, idempotent rewards, persistence, replay/reset and blocked/corrupt storage.');
