const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-logic/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}
const truth={and:[false,false,false,true],or:[false,true,true,true],not:[true,true,false,false]};
function explore(h){for(const k of h.c.combinations()){const x=k[0]==='1',y=k[1]==='1';if(h.run('a')!==x)h.c.toggle(0);if(k.length===2&&h.run('b')!==y)h.c.toggle(1);h.c.test();assert.equal(h.run('last'),truth[h.c.rule()][Number(x)*2+Number(y)]);}assert(h.c.ready());}
function finish(h){for(let s=0;s<3;s++){explore(h);h.c.choose(h.c.rule());assert(h.run('solved'));if(s<2)h.e.next.onclick();}assert(h.c.OrionProgress.has('truth'));}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{logic:v}}));assert(h.e.hints.hidden&&h.e.ruleChoices.hidden&&h.e.reward.hidden);h.c.choose(h.c.rule());assert(!h.run('solved'));h.c.toggle(5);assert(!h.run('a'));h.c.test();h.c.test();assert.equal(h.run('Object.keys(records).length'),1);h.e.retry.onclick();assert.equal(h.run('Object.keys(records).length'),0);h.e.hint.onclick();assert(!h.e.hints.hidden);const before=h.run('JSON.stringify([a,b,stage,variant,records])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([a,b,stage,variant,records])'),before);
 explore(h);h.c.choose(['and','or','not'].find(x=>x!==h.c.rule()));assert.equal(h.run('state'),'wrong');assert(!h.run('solved'));h.c.choose(h.c.rule());h.e.next.onclick();explore(h);h.c.choose(h.c.rule());h.e.next.onclick();explore(h);h.c.choose(h.c.rule());assert(h.c.OrionProgress.has('truth'));assert(h.c.OrionProgress.has('future'));h.c.choose(h.c.rule());assert.equal(h.c.OrionProgress.read().sigils.filter(x=>x==='truth').length,1);
 const saved=h.data['orion-expedition-progress-v1'];assert(setup(lang,saved).c.OrionProgress.has('truth'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('truth'));assert(h.e.reward.hidden&&h.e.hints.hidden);const old=h.run('variant');h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('truth'));assert.equal(h.run('stage'),0);finish(h);
}
const b=setup('en',null,true);finish(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('truth'));
for(const saved of ['broken','{"version":1,"sigils":[]}'])assert.equal(setup('en',saved).run('variant'),0);
const h=setup();for(const k of ['and','or','not'])for(let i=0;i<4;i++)assert.equal(h.c.outcome(k,!!(i&2),!!(i&1)),truth[k][i]);
console.log('PASS logic: independent truth tables, all six orders in both languages, premature/wrong choices, evidence/retry, hidden hints, language preservation, idempotent rewards, replay/reload/reset, corrupt and blocked storage.');
