const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-maze/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){for(const n of h.c.best().slice(1))h.c.choose(n);h.c.check();assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('wisdom'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{maze:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'incomplete');h.c.choose('T');h.c.choose('bad');assert.equal(h.run('path.length'),1);h.c.choose('A');h.c.choose('S');assert.equal(h.run('path.length'),2);h.c.undo();assert.equal(h.run('path.length'),1);h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('path.length'),1);solve(h);assert(h.c.OrionProgress.has('wisdom')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('wisdom'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('wisdom'));const old=h.run('variant');h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('wisdom'));assert.equal(h.run('stage'),0);
}
// Independent Floyd-Warshall oracle checks every simple route, including ties.
let checked=0,wins=0,losses=0;
for(let v=0;v<6;v++)for(let s=0;s<3;s++){const h=setup();h.run(`variant=${v};stage=${s};resetTrial()`);const names=['S','A','B','C','D','T'],pairs=[[0,1],[0,2],[1,3],[2,4],[1,2],[3,4],[3,5],[4,5]],w=Array.from(h.c.weights()),d=names.map((_,i)=>names.map((_,j)=>i===j?0:Infinity));pairs.forEach(([a,b],i)=>d[a][b]=d[b][a]=w[i]);for(let k=0;k<6;k++)for(let i=0;i<6;i++)for(let j=0;j<6;j++)d[i][j]=Math.min(d[i][j],d[i][k]+d[k][j]);for(const route of h.c.routes()){h.c.resetTrial();route.slice(1).forEach(n=>h.c.choose(n));const expected=h.c.total()===d[0][5];h.c.check();assert.equal(h.run('solved'),expected);checked++;expected?wins++:losses++;}assert.equal(h.c.total(h.c.best()),d[0][5]);}
assert(wins>=18&&losses>0);const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('wisdom'));assert.equal(setup('en','broken').run('variant'),0);
console.log(`PASS maze: ${checked} routes against independent shortest-path oracle, both languages, six sets, undo, hints, reward/persistence/reset, failed-save recovery.`);
