const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(language='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':language};if(saved)data['orion-expedition-progress-v1']=saved;const element=()=>({value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,open:false,attrs:{},style:{setProperty(){}},classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=v},listeners:{},addEventListener(k,f){this.listeners[k]=f},querySelector(){return {focus(){}}},focus(){}});const c={navigator:{language},Event:class{constructor(type){this.type=type}},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},document:{documentElement:{},getElementById:id=>e[id]??=element(),querySelectorAll:()=>[]},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:event=>(events[event.type]??[]).forEach(f=>f(event))};c.window=c;vm.createContext(c);for(const path of ['dist/shared/i18n.js','dist/shared/progress.js','dist/games/orion-mist/game.js'])vm.runInContext(fs.readFileSync(path,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}
function complete(h){for(let s=0;s<3;s++){let count=0;while(!h.run('solved')){const before=h.run('[low,high]');h.c.probe(Math.floor((before[0]+before[1])/2));assert(++count<=s+4);const target=h.run('targetFor(variant,stage)');assert(h.run('low')<=target&&h.run('high')>=target);}if(s<2)h.e.next.onclick();}assert(h.c.OrionProgress.has('mist'));}
for(const lang of ['en','zh-Hant'])for(let v=0;v<8;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{mist:v},hashTarget:0}));assert(h.e.hints.hidden);assert(h.e.reward.hidden);
 for(const bad of [0,9,-1,1.5,NaN,'3']){h.c.probe(bad);assert.equal(h.run('history.length'),0);assert(!h.run('solved'));}
 h.c.probe(1);const size=h.run('history.length');if(!h.run('solved')){h.c.probe(1);assert.equal(h.run('history.length'),size);}
 h.c.resetMission();h.e.hint.onclick();const target=h.run('targetFor(variant,stage)');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('targetFor(variant,stage)'),target);assert.equal(h.run('hintDepth'),1);h.e.retry.onclick();assert(h.e.hints.hidden);assert.equal(h.run('targetFor(variant,stage)'),target);
 complete(h);assert(h.c.OrionProgress.has('future'));assert.equal(h.e.progressBar.value,3);assert(!h.e.notes.hidden);h.c.probe(1);assert.equal(h.c.OrionProgress.read().sigils.length,2);
 const saved=h.data['orion-expedition-progress-v1'],reload=setup(lang,saved);assert.equal(reload.run('variant'),v);assert(reload.c.OrionProgress.has('mist'));
 h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('mist'));const replayVariant=h.run('variant');for(let s=0;s<3;s++)assert.notEqual(h.c.targetFor(v,s),h.c.targetFor(replayVariant,s));complete(h);
 h.c.OrionProgress.reset();h.c.dispatchEvent({type:'pageshow'});assert.notEqual(h.run('variant'),replayVariant);assert.equal(h.run('stage'),0);assert(h.e.reward.hidden);assert(h.e.hints.hidden);assert(!h.c.OrionProgress.has('mist'));complete(h);
}
// Independent exhaustive proof of interval shrinking and stated midpoint query bounds, including all endpoints.
for(const size of [8,16,32])for(let target=1;target<=size;target++){let lo=1,hi=size,queries=0;while(true){const mid=Math.floor((lo+hi)/2);queries++;if(mid===target)break;if(mid<target)lo=mid+1;else hi=mid-1;assert(lo<=target&&target<=hi);}assert(queries<=Math.floor(Math.log2(size))+1);}
const blocked=setup('en',undefined,true);complete(blocked);assert.match(blocked.e.saveStatus.textContent,/could not save/);assert(!blocked.e.retrySave.hidden);blocked.c.localStorage.setItem=(k,v)=>blocked.data[k]=v;blocked.e.retrySave.onclick();assert(blocked.e.retrySave.hidden);assert.match(blocked.e.saveStatus.textContent,/saved/);
const corrupt=setup('zh-Hant','bad json');complete(corrupt);
const other=setup();other.c.probe(1);const signature=other.run('JSON.stringify([stage,low,high,history])');other.c.OrionProgress.earn('echo');other.c.dispatchEvent({type:'storage',key:'orion-expedition-progress-v1'});assert.equal(other.run('JSON.stringify([stage,low,high,history])'),signature);other.c.OrionProgress.reset();other.c.dispatchEvent({type:'storage',key:'orion-expedition-progress-v1'});assert.equal(other.run('history.length'),0);
console.log('PASS mist: all eight variants in both languages, three shores, invalid/excluded guesses, interval evidence, exhaustive midpoint bounds, retry, hidden hints, persistence, replay/reset, unknown sigils, blocked/corrupt storage and save retry.');
