const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-pollination/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){h.c.collect((h.c.target()+1)%3);h.c.deliver('stigma');assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('blossom'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{pollination:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.deliver('stigma');assert.equal(h.run('state'),'empty');for(const n of [-1,4,NaN])h.c.collect(n);assert.equal(h.run('pollen'),null);h.c.collect(3);h.c.deliver('stigma');assert.equal(h.run('state'),'species');h.e.hint.onclick();h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('pollen'),3);assert(!h.e.hints.hidden);h.e.retry.onclick();assert(h.e.hints.hidden);solve(h);assert(h.c.OrionProgress.has('blossom')&&h.c.OrionProgress.has('future'));h.c.deliver('stigma');assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('blossom'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('blossom'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('blossom'));}
// Independent compatibility matrix: selected apple varieties A/B/C cross-compatible, pear excluded.
const compatible=[[false,true,true,false],[true,false,true,false],[true,true,false,false]],journeys=new Set();let tests=0;for(let v=0;v<6;v++){const h=setup();h.run(`variant=${v}`);journeys.add([0,1,2].map(s=>h.c.target(v,s)).join());for(let s=0;s<3;s++)for(let donor=0;donor<4;donor++)for(const part of ['stigma','anther','petals']){h.run(`stage=${s};resetTrial()`);h.c.collect(donor);h.c.deliver(part);assert.equal(h.run('solved'),part==='stigma'&&compatible[h.c.target()][donor]);tests++;}}assert.equal(journeys.size,6);
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('blossom'));assert.equal(setup('en','broken').run('variant'),0);
console.log(`PASS pollination: ${tests} donor/destination trials, six sets, both languages, retry/hints, all-three reward, persistence/reset and failed saves.`);
