const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-shadows/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){const g=h.c.target();h.c.moveLight((g.direction+2)%4);h.c.raiseLight(g.short);h.c.check();assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('sunshadow'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<8;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{shadows:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'wrong');const initial=h.run('JSON.stringify([direction,height])');h.c.moveLight(99);h.c.raiseLight(NaN);assert.equal(h.run('JSON.stringify([direction,height])'),initial);h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.moveLight(1);h.e.retry.onclick();assert.equal(h.run('JSON.stringify([direction,height])'),initial);assert(h.e.hints.hidden);const snap=h.run('JSON.stringify([stage,direction,height,variant])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([stage,direction,height,variant])'),snap);solve(h);assert(h.c.OrionProgress.has('sunshadow')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('sunshadow'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('sunshadow'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('sunshadow'));assert.equal(h.run('stage'),0);
}
// Independent cardinal-direction oracle and all 192 trial combinations.
const opposite=[2,3,0,1];
for(let v=0;v<8;v++)for(let s=0;s<3;s++)for(let d=0;d<4;d++)for(let ht=0;ht<2;ht++){
 const h=setup();h.run(`variant=${v};stage=${s};resetTrial()`);h.c.moveLight(d);h.c.raiseLight(ht);assert.equal(h.c.shadow().direction,opposite[d]);assert.equal(h.c.shadow().short,ht);h.c.check();assert.equal(h.run('solved'),opposite[d]===(v+s)%4&&ht===(Math.floor(v/4)+s)%2);
}
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('sunshadow'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS shadows: 192 trial combinations, eight sets, both languages, wrong/retry/hints, rewards, persistence, replay/reset and failed saves.');
