const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-signal/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){h.c.toggle(4);h.c.check();assert(h.run('solved'));h.e.next.onclick();h.c.toggle(0);h.c.check();h.c.answer(true);assert(h.run('solved'));assert(!h.c.OrionProgress.has('starspeech'));h.e.next.onclick();h.c.toggle(0);h.c.toggle(1);h.c.check();h.c.answer(false);assert(h.run('solved'));}
for(const lang of ['en','zh-Hant'])for(let v=0;v<8;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{signal:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'wrong');const initial=h.run('JSON.stringify(bits)');for(const n of [-1,0,9,NaN])h.c.toggle(n);assert.equal(h.run('JSON.stringify(bits)'),initial);h.c.answer(false);assert(!h.run('solved'));h.e.hint.onclick();assert(!h.e.hints.hidden);h.e.retry.onclick();assert(h.e.hints.hidden);h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify(bits)'),initial);solve(h);assert(h.c.OrionProgress.has('starspeech')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('starspeech'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('starspeech'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('starspeech'));assert.equal(h.run('stage'),0);
}
// Independent parity oracle over every possible 5-bit flip mask, in all 8 sets.
const rows=new Set();
for(let v=0;v<8;v++){const h=setup();h.run(`variant=${v};stage=1;resetTrial()`);const original=Array.from(h.c.source());rows.add(original.join(''));assert.equal(original.reduce((a,b)=>a+b,0)%2,0);for(let mask=0;mask<32;mask++){h.c.resetTrial();let changes=0;for(let i=0;i<5;i++)if(mask&(1<<i)){h.c.toggle(i);changes++;}assert.equal(h.c.alarm(),changes%2===1);assert.equal(h.c.flips(),changes);h.c.check();assert.equal(h.run('tested'),changes===1);if(changes===1){h.c.answer(false);assert(!h.run('solved'));h.c.answer(true);assert(h.run('solved'));}}}assert.equal(rows.size,8);
const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('starspeech'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS signal: 256 flip masks, eight sets, bilingual hints, invalid/wrong/retry, complete reward, persistence/reset and failed-save recovery.');
