const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-sort/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){const a=JSON.parse(h.run('JSON.stringify(cars)')),want=[...a].sort((x,y)=>s===1?y-x:x-y);for(let i=0;i<a.length;i++){if(a[i]!==want[i]){const j=a.findIndex((n,k)=>k>i&&n===want[i]);h.c.choose(i);h.c.choose(j);[a[i],a[j]]=[a[j],a[i]];}}h.c.check();assert(h.run('solved'));if(s<2){assert(!h.c.OrionProgress.has('order'));h.e.next.onclick();}}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{sort:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'wrong');h.c.choose(-1);h.c.choose(20);h.c.choose(0.5);assert.equal(h.run('selected'),null);h.c.choose(0);h.c.choose(0);assert.equal(h.run('selected'),null);h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.choose(0);h.c.choose(1);h.e.retry.onclick();assert.equal(h.run('JSON.stringify(cars)'),JSON.stringify(h.c.initial()));assert(h.e.hints.hidden);h.c.choose(0);const snap=h.run('JSON.stringify([stage,cars,variant,selected,history])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([stage,cars,variant,selected,history])'),snap);h.c.choose(0);solve(h);assert(h.c.OrionProgress.has('order')&&h.c.OrionProgress.has('future'));h.c.check();h.c.choose(0);assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('order'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('order'));const old=h.run('variant');assert.equal(setup(lang,h.data['orion-expedition-progress-v1']).run('variant'),old);h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('order'));assert.equal(h.run('stage'),0);
}
const h=setup();assert(h.c.inOrder([1,1,2],0));assert(!h.c.inOrder([1,3,2],0));assert(h.c.inOrder([3,2,2,1],1));assert(!h.c.inOrder([3,1,2],1));for(let v=0;v<6;v++)for(let s=0;s<3;s++)assert(!h.c.inOrder(h.c.initial(v,s),s));const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('order'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS sorting: six complete sets, ascending/descending/equal values, both languages, invalid/wrong/cancel/retry paths, hints, reward persistence, replay/reset and storage failures.');
