const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
function setup(lang='en',saved,blocked=false){const e={},events={},data={'orion-expedition-language':lang};if(saved)data['orion-expedition-progress-v1']=saved;const el=()=>({textContent:'',innerHTML:'',hidden:false,disabled:false,value:0,open:false,classList:{toggle(){}},setAttribute(){},addEventListener(){},focus(){}});const c={navigator:{language:lang},Event:class{constructor(type){this.type=type}},document:{body:{},documentElement:{},getElementById:id=>e[id]??=el(),querySelectorAll:()=>[]},localStorage:{getItem:k=>data[k]??null,setItem(k,v){if(blocked)throw Error('blocked');data[k]=v}},addEventListener:(k,f)=>(events[k]??=[]).push(f),dispatchEvent:x=>(events[x.type]??[]).forEach(f=>f(x))};c.window=c;vm.createContext(c);for(const f of ['shared/i18n.js','shared/progress.js','games/orion-water/game.js'])vm.runInContext(fs.readFileSync('dist/'+f,'utf8'),c);return{c,e,data,run:s=>vm.runInContext(s,c)};}

function solve(h){for(let s=0;s<3;s++){let budget=3;while(h.run('phase')!==h.c.target()&&budget--)h.c.act(h.run('phase')<h.c.target()?1:-1);h.c.check();assert(h.run('solved'));if(s<2)h.e.next.onclick();}}
for(const lang of ['en','zh-Hant'])for(let v=0;v<6;v++){
 const h=setup(lang,JSON.stringify({version:1,sigils:['future'],variants:{water:v}}));assert(h.e.hints.hidden&&h.e.reward.hidden);h.c.check();assert.equal(h.run('state'),'wrong');h.c.act(99);assert.equal(h.run('phase'),h.c.initial());h.e.hint.onclick();assert(!h.e.hints.hidden);h.c.act(1);h.e.retry.onclick();assert.equal(h.run('phase'),h.c.initial());assert(h.e.hints.hidden);const snapshot=h.run('JSON.stringify([stage,phase,variant,history])');h.c.OrionI18n.set(lang==='en'?'zh-Hant':'en');assert.equal(h.run('JSON.stringify([stage,phase,variant,history])'),snapshot);solve(h);assert(h.c.OrionProgress.has('transformation')&&h.c.OrionProgress.has('future'));h.c.check();assert.equal(h.c.OrionProgress.read().sigils.length,2);assert(setup(lang,h.data['orion-expedition-progress-v1']).c.OrionProgress.has('transformation'));h.e.replay.onclick();assert.notEqual(h.run('variant'),v);assert(h.c.OrionProgress.has('transformation'));const old=h.run('variant');h.c.OrionProgress.reset();h.c.syncProgress();assert.notEqual(h.run('variant'),old);assert(!h.c.OrionProgress.has('transformation'));assert.equal(h.run('stage'),0);
}
const h=setup();for(let p=0;p<3;p++){assert.equal(h.c.transition(p,1),[1,2,2][p]);assert.equal(h.c.transition(p,-1),[0,0,1][p]);}const b=setup('en',null,true);solve(b);assert(b.run('saveFailed'));assert.match(b.e.saveStatus.textContent,/failed/);b.c.localStorage.setItem=(k,v)=>b.data[k]=v;b.e.retrySave.onclick();assert(!b.run('saveFailed'));assert(setup('en',b.data['orion-expedition-progress-v1']).c.OrionProgress.has('transformation'));assert.equal(setup('en','broken').run('variant'),0);
console.log('PASS water: all phase transitions and six solvable journeys, both languages, invalid/wrong/retry paths, hidden hints, reward persistence, replay/reset, future sigils and blocked/corrupt storage.');
